spring:
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:test/changelog-master.xml
    enabled: true
    drop-first: true